[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.68"

[[constraint]]
  name = "github.com/golang/mock"
  revision = "b3e60bcdc577185fce3cf625fc96b62857ce5574"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/golang-lru"

[[constraint]]
  name = "github.com/kyokomi/emoji"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "ccaecb155a2177302cb56cae929251a256d0f646"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"
